### ISSUE TITLE
Some links are broken

### ISSUE THREAD

**Issue by ndsvw** [r0f1/datascience#39]
Hello, I found some broken hyperlinks:
- [x] https://pythonfordatascience.org/anova-python/ (file: README.md, error: ECONNRESET)
- [x] https://pythonfordatascience.org/anova-2-way-n-way/ (file: README.md, error: ECONNRESET)
- [x] https://online.stat.psu.edu/stat509/node/75/ (file: README.md, status code: 404)
- [x] https://lambdaclass.com/data_etudes/central_limit_theorem_misuse/ (file: README.md, status code: 404)
- [x] http://www-stat.wharton.upenn.edu/~hwainer/Readings/Most%20Dangerous%20eqn.pdf (file: README.md, status code: 404)
- [x] https://w2v-vis-dot-hcg-team-di.appspot.com/#/galaxy/word2vec?cx=5698&cy=-5135&cz=5923&lx=0.1127&ly=0.3238&lz=-0.1680&lw=0.9242&ml=150&s=1.75&l=1&v=hc (file: README.md, status code: 404)
- [x] https://awesome-streamlit.org/ (file: README.md, error: CERT_HAS_EXPIRED)
- [x] https://tech.minodes.com/experiments-with-in-memory-spatial-radius-queries-in-python-e40c9e66cf63 (file: README.md, error: CERT_HAS_EXPIRED)
- [x] https://github.com/njanakiev/osm-predict-economic-measurements/blob/master/osm-predict-economic-indicators.ipynb (file: README.md, status code: 404)
- [x] https://github.com/mapequation/infomap/blob/master/examples/python/infomap-examples.ipynb (file: README.md, status code: 404)
- [x] https://github.com/welch-lab/pyliger/blob/master/pyliger/factorization/_iNMF_ANLS.py#L65 (file: README.md, status code: 404)
- [x] https://course.fast.ai/videos/?lesson=1 (file: README.md, status code: 404)
- [x] https://vis.ensmallen.org/ (file: README.md, error: CERT_HAS_EXPIRED)
- [x] https://github.com/zjohn77/buckshotpp (file: README.md, status code: 404)
- [x] https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/timeseries (file: README.md, status code: 404)
- [x] https://github.com/slundberg/shap/blob/master/notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.ipynb (file: README.md, status code: 404)
- [x] https://pastas.readthedocs.io/en/latest/examples.html (file: README.md, status code: 404)
- [x] https://scipy.github.io/devdocs/generated/scipy.stats.entropy.html (file: README.md, status code: 404)
- [x] https://docs.pymc.io/notebooks/getting_started (file: README.md, status code: 404)
- [x] https://www.kaggle.com/divrikwicky/pf-f-lofo-importance-on-adversarial-validation (file: README.md, status code: 404)
- [x] https://www.kaggle.com/divrikwicky/lofo-importance (file: README.md, status code: 404)
- [x] https://www.kaggle.com/divrikwicky/santanderctp-lofo-feature-importance (file: README.md, status code: 404)
- [x] https://github.com/aljabr0/hypergraph (file: README.md, status code: 404)
- [x] https://github.com/kdhht2334/Survey_of_Deep_Metric_Learning (file: README.md, status code: 404)
- [x] https://github.com/amitness/toolbox (file: README.md, status code: 404)
- [x] https://github.com/blue-yonder/tsfresh/blob/master/tsfresh/feature_extraction/feature_calculators.py (file: README.md, status code: 404)

**Comment by r0f1** [comment]
Thank you very much! That is really helpful. I will address these issues.

**Comment by ndsvw** [comment]
Awesome!
